#!/bin/sh

chmod 755 /etc/init.d/frp

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@frp[-1]
	add ucitrack frp
	set ucitrack.@frp[-1].init=frp
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
